name: Deploy API to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    # Only run deployment on push to main/master, not on PRs
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Ruff (lint)
        working-directory: ./api
        run: ruff check .

      - name: Mypy (type-check)
        working-directory: ./api
        run: mypy .

      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only --app api-broken-moon-5814
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./api # Run deployment from api folder

