name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  publish-gh-pages:
    name: Publish to GitHub pages
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Set up
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-modules
        uses: actions/cache@v2
        env:
          cache-name: ${{ github.event.repository.name }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        with:
          path: 'node_modules'
          key: ${{ runner.os }}-${{ github.event.repository.name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm run build

      - name: Deploy to GH
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          target-folder: ${{ github.head_ref }}
