name: Deploy All Services

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  # Deploy Frontend to GitHub Pages
  deploy-frontend:
    name: Deploy Frontend to GitHub Pages
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          CI: false  # Ignore warnings during build
          GENERATE_SOURCEMAP: false

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true

  # Deploy API to Fly.io (only if api directory exists and has changes)
  deploy-api:
    name: Deploy API to Fly.io
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if API directory exists
        id: check_api
        run: |
          if [ -d "api" ]; then
            echo "api_exists=true" >> $GITHUB_OUTPUT
          else
            echo "api_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Fly.io CLI
        if: steps.check_api.outputs.api_exists == 'true' && secrets.FLY_API_TOKEN != ''
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        if: steps.check_api.outputs.api_exists == 'true' && secrets.FLY_API_TOKEN != ''
        run: flyctl deploy --remote-only --app api-broken-moon-5814
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        working-directory: ./api
