name: Deploy to GH
on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  publish-gh-pages:
    name: Publish to GitHub pages
    runs-on: ubuntu-latest

    steps:

      - name: Set up
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy to GH
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          target-folder: ${{ github.head_ref }}
