name: Deploy Frontend to GitHub Pages and API to Fly.io

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-frontend:
    name: Deploy Frontend to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to GitHub Pages (gh-pages branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true

  deploy-api:
    name: Deploy API to Fly.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if API directory exists
        id: check_api
        run: |
          if [ -f "api/fly.toml" ]; then
            echo "run_api=true" >> $GITHUB_OUTPUT
          else
            echo "run_api=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Fly.io CLI
        if: ${{ steps.check_api.outputs.run_api == 'true' }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy API
        if: ${{ steps.check_api.outputs.run_api == 'true' }}
        working-directory: ./api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
