name: Deploy Landing Page to GitHub Pages

on:
  push:
    branches: [master]
  # Not sure if we want to deploy on PRs as we might break what's currently working...
  # pull_request:
  #   branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install and Build
        run: |
          cd src/landing-page
          yarn
          yarn build
      # TODO: Having deploy in same stage isn't great, worthwhile looking into uploading build artefact and deploying as a separate stage
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: src/landing-page/build # The folder the action should deploy.
